export const ROUTES = [
  "Perjalanan Menuju Innovation Station (sampe duduk)",
  "Opening Speech Officer 1",
  "Safety induction",
  "Speech officer 1",
  "Hologram",
  "Speech officer 1",
  "Tap gelang (termasuk baris)",
  "Speech officer 1",
  "Menuju Peron 1",
  "Opening Speech officer 3 (sampai duduk)",
  "Content Trip 1",
  "Closing Speech Officer 3",
  "Content Clevo Cow",
  "Briefing Speech officer 4",
  "Perjalanan menuju ruang 3D (sampai baris)",
  "Opening Speech officer 4",
  "Content & 3 Game",
  "Close Speech Officer 4",
  "Menuju Space (sampai duduk di space)",
  "Opening Speech officer 5 & 6",
  "Content & Game",
  "Closing Speech officer 5 & 6",
  "Menuju peron 2",
  "Opening Speech officer 3",
  "Content",
  "Closing Speech officer 3",
  "Speech officer 7 & 8 Tunnel 1 (sampai turun tangga)",
  "Speech officer 7 & 8 Tunnel 2 (sampai buka pintu chamber)",
  "Opening Speech Officer 9 (tidak ada)",
  "Content (tidak ada)",
  "Menuju Briefing Room (sampai baris)",
  "Opening Speech Officer 10",
  "Content",
  "Closing Speech Officer 9",
  "Foto-foto / Freetime (tidak ada)",
  "Menuju Gondola (sampai baris)",
  "Opening Speech officer 10",
  "Peserta naik Gondola",
  "Briefing Officer 10",
  "Content & Game",
  "Peserta Turun Gondola (termasuk pengumpulan band)",
  "Keluar Gondola (berbaris menuju photo booth)"
];
